"""Add 2FA and email functionality models

Revision ID: 22520876f811
Revises: 185081d296a9
Create Date: 2025-09-18 21:47:38.171215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22520876f811'
down_revision = '185081d296a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('two_factor_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('attempt_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('two_factor_auth',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('secret_key', sa.String(length=32), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('backup_codes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('two_factor_auth')
    op.drop_table('two_factor_attempts')
    # ### end Alembic commands ###
