"""card migrations

Revision ID: 3921afe25998
Revises: 0c41b7b77f98
Create Date: 2025-09-09 17:42:51.709326

"""
from alembic import op
import sqlalchemy as sa
from app.utils.guid_utils import GUID


# revision identifiers, used by Alembic.
revision = '3921afe25998'
down_revision = '0c41b7b77f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_card',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('account_id', GUID(), nullable=False),
    sa.Column('card_kind', sa.String(length=50), nullable=False),
    sa.Column('card_type', sa.String(length=50), nullable=False),
    sa.Column('card_holder', sa.String(length=180), nullable=False),
    sa.Column('card_number', sa.LargeBinary(), nullable=False),
    sa.Column('card_number_hash', sa.String(length=64), nullable=False),
    sa.Column('expiration_date', sa.String(length=7), nullable=False),
    sa.Column('cvv', sa.LargeBinary(), nullable=False),
    sa.Column('pin', sa.LargeBinary(), nullable=False),
    sa.Column('spending_limit', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_number_hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virtual_card')
    # ### end Alembic commands ###
