"""Add Stripe integration fields to virtual cards and payment intents

Revision ID: 4c8cbca8c145
Revises: 7489757f44b3
Create Date: 2025-09-12 16:43:42.892802

"""
from alembic import op
import sqlalchemy as sa
from app.utils.guid_utils import GUID


# revision identifiers, used by Alembic.
revision = '4c8cbca8c145'
down_revision = '7489757f44b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_intents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('virtual_card_id', GUID(), nullable=True))
        batch_op.create_foreign_key('fk_payment_intents_virtual_card_id', 'virtual_card', ['virtual_card_id'], ['id'])

    with op.batch_alter_table('virtual_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_payment_method_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_card', schema=None) as batch_op:
        batch_op.drop_column('stripe_payment_method_id')

    with op.batch_alter_table('payment_intents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payment_intents_virtual_card_id', type_='foreignkey')
        batch_op.drop_column('virtual_card_id')

    # ### end Alembic commands ###
