"""add_email_verification_fields_to_user

Revision ID: 5118c9068212
Revises: c07b0b6e245d
Create Date: 2025-09-22 20:35:34.241370

"""
from alembic import op
import sqlalchemy as sa
from app.utils.guid_utils import GUID


# revision identifiers, used by Alembic.
revision = '5118c9068212'
down_revision = 'c07b0b6e245d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
